// ============================================================================
// Mock pmkit Artifacts - outputs from previous job runs
// These can be used as inputs to subsequent jobs (artifact chaining)
// ============================================================================

export interface PmkitArtifact {
  id: string;
  type: 'prd' | 'brief' | 'voc_report' | 'competitor_report' | 'alignment_memo' | 'sprint_review' | 'prototype';
  title: string;
  jobId: string;
  createdAt: string;
  content: string;
  metadata?: Record<string, unknown>;
}

export const pmkitData = {
  artifacts: [
    {
      id: 'artifact-prd-001',
      type: 'prd' as const,
      title: 'PRD: Search Filters',
      jobId: 'job-prd-001',
      createdAt: '2026-01-08T14:30:00Z',
      content: `# PRD: Search Filters

**Author**: Demo User
**Date**: January 8, 2026
**Status**: Approved
**Epic**: ACME-100

---

## 1. Overview

### Problem Statement

Users cannot efficiently find content because search results lack filtering capabilities. This leads to:
- Wasted time scrolling through irrelevant results
- Workarounds using manual tagging systems
- Frustration and reduced product satisfaction

### Goals

| Goal | Metric | Target |
|------|--------|--------|
| Reduce time to find content | Avg. search-to-click time | -30% |
| Improve search satisfaction | User survey score | 3.2 → 4.0+ |
| Reduce no-results frustration | Filter usage rate | >40% of searches |

### Non-Goals

- AI-powered semantic search (future initiative)
- Saved searches (separate feature)
- Search analytics dashboard (admin feature)

---

## 2. Background

### Customer Evidence

| Source | Count | Key Quote |
|--------|-------|-----------|
| Support tickets | 47 | "I spend more time searching than working" |
| Gong calls | 12 | "Date filters would be huge" |
| Community | 89 votes | "Filter by content type please" |

### Market Context

All major competitors (Notion, Coda, Monday.com) offer search filters. This is table-stakes functionality.

---

## 3. Solution

### Proposed Approach

Add filter controls to search results with:
- Date range filter (Last 7d, 30d, 90d, custom)
- Content type filter (Documents, Projects, Comments)
- Project/Space filter

### User Stories

1. **As a PM**, I want to filter search by date range so I can find recent content quickly
2. **As a PM**, I want to filter by content type so I can focus on documents vs comments
3. **As a PM**, I want to combine multiple filters so I can narrow results precisely

### Key Flows

1. User enters search query
2. Results display with filter bar above
3. User selects filter(s)
4. Results update in real-time
5. Filters persist during session

---

## 4. Requirements

### Functional Requirements

| ID | Requirement | Priority |
|----|-------------|----------|
| F1 | Date range filter with presets | P0 |
| F2 | Custom date range picker | P1 |
| F3 | Content type filter | P0 |
| F4 | Project/space filter | P1 |
| F5 | Filter combination (AND logic) | P0 |
| F6 | Clear all filters action | P0 |
| F7 | Filter state in URL | P2 |

### Non-Functional Requirements

- Filter application < 200ms
- Support 100k+ documents
- Mobile-responsive design

---

## 5. Success Criteria

### Launch Criteria
- [ ] All P0 requirements complete
- [ ] <1% error rate in filter queries
- [ ] Performance within targets
- [ ] Documentation updated

### Success Metrics (30 days post-launch)
- Filter usage rate > 40%
- Search satisfaction +0.5 points
- No increase in support tickets

---

## 6. Open Questions

1. Should we index comments? (performance vs completeness)
2. How to handle permission-filtered results in counts?
3. What's the default date range?

---

*Generated by pmkit PRD Draft • January 8, 2026*`,
      metadata: {
        featureName: 'Search Filters',
        epicKey: 'ACME-100',
        sources: ['zendesk', 'gong', 'discourse'],
        toolCalls: 4,
      },
    },
    {
      id: 'artifact-prd-002',
      type: 'prd' as const,
      title: 'PRD: Enterprise SSO',
      jobId: 'job-prd-002',
      createdAt: '2026-01-06T10:15:00Z',
      content: `# PRD: Enterprise SSO

**Author**: Demo User
**Date**: January 6, 2026
**Status**: Draft
**Epic**: ACME-200

---

## 1. Overview

### Problem Statement

Enterprise customers cannot use their corporate identity providers to authenticate, blocking deals worth $450K ARR.

### Goals

| Goal | Metric | Target |
|------|--------|--------|
| Unblock enterprise deals | Deals closed | 3 deals ($450K) |
| Reduce IT friction | Time to onboard | <1 day |
| Improve security posture | SSO adoption | >80% enterprise users |

---

## 2. Customer Evidence

| Source | Evidence |
|--------|----------|
| Sales pipeline | 3 deals blocked on SSO |
| Gong calls | "We can't proceed without SAML" |
| Security reviews | 5 failed due to no SSO |

---

## 3. Requirements

### Functional Requirements

| ID | Requirement | Priority |
|----|-------------|----------|
| F1 | SAML 2.0 support | P0 |
| F2 | OIDC support | P0 |
| F3 | JIT user provisioning | P1 |
| F4 | Group-to-role mapping | P1 |

---

*Generated by pmkit PRD Draft • January 6, 2026*`,
      metadata: {
        featureName: 'Enterprise SSO',
        epicKey: 'ACME-200',
        sources: ['gong', 'jira'],
        toolCalls: 3,
      },
    },
    {
      id: 'artifact-voc-001',
      type: 'voc_report' as const,
      title: 'VoC Report - Q4 2025',
      jobId: 'job-voc-001',
      createdAt: '2026-01-05T09:00:00Z',
      content: `# Voice of Customer Report - Q4 2025

**Period**: October - December 2025
**Generated**: January 5, 2026
**Data Sources**: Zendesk (156 tickets), Gong (89 calls), Discourse (234 posts)

---

## Executive Summary

| Theme | Mentions | Trend | Impact |
|-------|----------|-------|--------|
| Search Frustration | 52 | ↑ 15% | Critical |
| Onboarding Complexity | 33 | → Stable | High |
| Integration Gaps | 27 | ↓ 8% | Medium |
| Performance Issues | 22 | ↑ 25% | High |

---

## Top Themes

### 1. Search Frustration (52 mentions)

**Representative Quotes**:
> "I spend more time searching than working" - Globex Corp
> "Search never finds what I'm looking for" - Community
> "We've created workarounds using tags but it's not sustainable" - Initech

**Product Implications**:
- Search improvements are critical for retention
- Filters are table-stakes expectation
- Enterprise expansion blocked

### 2. Onboarding Complexity (33 mentions)

**Representative Quotes**:
> "It took our team 3 weeks to get productive" - Gong call
> "The learning curve is steep" - NPS verbatim

### 3. Integration Gaps (27 mentions)

- Slack sync reliability issues
- Jira two-way sync requested
- Calendar integration gaps

### 4. Performance Issues (22 mentions)

- Dashboard loading slow for large accounts
- Search latency on 100k+ document accounts

---

## Recommendations

1. **Ship search improvements** (In Progress - Sprint 42)
2. **Redesign onboarding flow** - High impact, medium effort
3. **Rebuild Slack integration** - Address reliability concerns
4. **Performance optimization** - Focus on enterprise accounts

---

*Generated by pmkit VoC Clustering • January 5, 2026*`,
      metadata: {
        period: 'Q4 2025',
        sources: ['zendesk', 'gong', 'discourse'],
        totalMentions: 134,
        themes: 4,
      },
    },
    {
      id: 'artifact-brief-001',
      type: 'brief' as const,
      title: 'Daily Brief - January 9, 2026',
      jobId: 'job-brief-001',
      createdAt: '2026-01-09T08:00:00Z',
      content: `# Daily Brief - January 9, 2026

## TL;DR
Search filters shipped successfully with 34% adoption in first 48 hours. One P1 bug (ACME-350) resolved. Globex Corp expansion discussion scheduled for tomorrow.

## 🚨 Urgent Items

None - all P1s resolved.

## 📊 Sprint Progress (Sprint 42)

| Story | Status | Points |
|-------|--------|--------|
| ACME-342: Search filters | ✅ Shipped | 5 |
| ACME-343: Search ranking | ✅ Shipped | 8 |
| ACME-344: No results UX | In Progress | 3 |

**Velocity**: 13/19 points complete (68%)

## 📣 Customer Signal

- **Positive**: 12 mentions of search filters in community
- **Globex Corp**: Ready to discuss 4x expansion
- **Feature request**: Custom date ranges (5 mentions)

## ✅ Recommended Actions

1. Prepare for Globex expansion call
2. Review custom date range scope
3. Close out Sprint 42 items

---

*Generated by pmkit Daily Brief • January 9, 2026*`,
      metadata: {
        sources: ['slack', 'jira', 'zendesk', 'discourse'],
        toolCalls: 4,
      },
    },
    {
      id: 'artifact-competitor-001',
      type: 'competitor_report' as const,
      title: 'Competitor Research - January 2026',
      jobId: 'job-competitor-001',
      createdAt: '2026-01-07T16:00:00Z',
      content: `# Competitor Research Report - January 2026

**Period**: Last 14 days
**Generated**: January 7, 2026

---

## Key Changes Summary

| Competitor | Change | Significance |
|------------|--------|--------------|
| Notion | AI-powered search launch | 🔴 High |
| Coda | 20% enterprise price cut | 🔴 High |
| Monday.com | Native Slack integration | 🟡 Medium |

---

## Feature Gap Analysis

| Feature | Us | Notion | Coda | Monday |
|---------|-----|--------|------|--------|
| AI Search | ❌ | ✅ | ❌ | ❌ |
| Search Filters | ✅ | ✅ | ✅ | ✅ |
| SAML SSO | 🔜 | ✅ | ✅ | ✅ |

---

## Recommended Actions

1. **Prioritize AI search discovery** - Notion has set new bar
2. **Monitor Coda pricing impact** - Track win/loss rates
3. **Accelerate SSO** - Table stakes for enterprise

---

*Generated by pmkit Competitor Research • January 7, 2026*`,
      metadata: {
        competitors: ['notion', 'coda', 'monday'],
        sources: ['web_search', 'social_crawler', 'news_crawler'],
      },
    },
  ] satisfies PmkitArtifact[],
};

// ============================================================================
// Helper Functions
// ============================================================================

export function getArtifactById(id: string): PmkitArtifact | undefined {
  return pmkitData.artifacts.find((a) => a.id === id);
}

export function getArtifactsByType(type: PmkitArtifact['type']): PmkitArtifact[] {
  return pmkitData.artifacts.filter((a) => a.type === type);
}

export function getRecentArtifacts(limit: number = 5): PmkitArtifact[] {
  return [...pmkitData.artifacts]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
}

export function searchArtifacts(query: string): PmkitArtifact[] {
  const lowerQuery = query.toLowerCase();
  return pmkitData.artifacts.filter(
    (a) =>
      a.title.toLowerCase().includes(lowerQuery) ||
      a.content.toLowerCase().includes(lowerQuery)
  );
}
