'use client';

import * as React from 'react';
import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import {
  Copy,
  Check,
  FileText,
  Code,
  Share2,
} from 'lucide-react';
import type { JobType, CrawlerType } from '@pmkit/core';

// Local analysis type that matches what the workbench provides
interface ShareableCrawlerAnalysis {
  summary: string;
  overallSentiment: 'positive' | 'negative' | 'neutral' | 'mixed';
  sentimentBreakdown: {
    positive: number;
    negative: number;
    neutral: number;
  };
  themes: Array<{
    name: string;
    description: string;
    mentionCount: number;
    sentiment: 'positive' | 'negative' | 'neutral' | 'mixed';
    keyQuotes: string[];
    sources: string[];
  }>;
  insights: Array<{
    type: 'opportunity' | 'threat' | 'trend' | 'action_item';
    title: string;
    description: string;
    priority: 'high' | 'medium' | 'low';
    evidence: string[];
  }>;
  competitorMentions: Array<{
    competitor: string;
    context: string;
    sentiment: 'positive' | 'negative' | 'neutral' | 'mixed';
    source: string;
    url?: string;
  }>;
  topQuotes: Array<{
    quote: string;
    source: string;
    url?: string;
    relevance: string;
  }>;
  recommendations: string[];
}

// Types for shareable content
export interface ShareableJobResult {
  type: 'job';
  jobType: JobType;
  content: string;
  timestamp: Date;
  metadata: {
    model: string;
    latencyMs: number;
    usage: {
      inputTokens: number;
      outputTokens: number;
      totalTokens: number;
    };
    estimatedCostUsd: number;
    isStub: boolean;
  };
  context?: Record<string, string>;
}

export interface ShareableCrawlerResult {
  type: 'crawler';
  crawlerType: CrawlerType;
  keywords: string[];
  urls?: string[];
  platforms: string[];
  resultCount: number;
  analysis: ShareableCrawlerAnalysis | null;
  createdAt: string;
  completedAt?: string;
  analysisMetadata?: {
    model: string;
    usage: {
      inputTokens: number;
      outputTokens: number;
      totalTokens: number;
    };
    latencyMs: number;
    estimatedCostUsd: number;
    isStub: boolean;
  };
}

export type ShareableContent = ShareableJobResult | ShareableCrawlerResult;

interface ShareDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  content: ShareableContent | null;
  tenantName?: string;
  productName?: string;
}

// Job type display names
const JOB_TYPE_NAMES: Record<JobType, string> = {
  daily_brief: 'Daily Brief',
  meeting_prep: 'Meeting Prep',
  feature_intelligence: 'Feature Intelligence',
  competitor_research: 'Competitor Research',
  roadmap_alignment: 'Roadmap Alignment',
  prd_draft: 'PRD Draft',
  sprint_review: 'Sprint Review',
  prototype_generation: 'PRD to Prototype',
  release_notes: 'Release Notes',
  deck_content: 'Deck Content',
};

// Crawler type display names
const CRAWLER_TYPE_NAMES: Record<CrawlerType, string> = {
  social: 'Social Crawler',
  web_search: 'Web Search',
  news: 'News Crawler',
  url_scrape: 'URL Scraper',
};

export function ShareDialog({
  open,
  onOpenChange,
  content,
  tenantName = 'My Company',
  productName = 'My Product',
}: ShareDialogProps) {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

  if (!content) return null;

  const isJob = content.type === 'job';
  const isPrototype = isJob && content.jobType === 'prototype_generation';
  const title = isJob
    ? JOB_TYPE_NAMES[content.jobType]
    : CRAWLER_TYPE_NAMES[content.crawlerType];

  // Generate markdown content
  const generateMarkdown = (): string => {
    const date = new Date().toISOString().split('T')[0];

    if (isJob) {
      const job = content as ShareableJobResult;
      const header = `# ${title}

**Generated by pmkit** | ${date}
**Company:** ${tenantName} | **Product:** ${productName}

---

`;
      return header + job.content;
    } else {
      const crawler = content as ShareableCrawlerResult;
      const analysis = crawler.analysis;

      let md = `# ${title} Results

**Generated by pmkit** | ${date}
`;

      if (crawler.urls && crawler.urls.length > 0) {
        md += `**URLs:** ${crawler.urls.join(', ')}\n`;
      } else {
        md += `**Keywords:** ${crawler.keywords.join(', ')}\n`;
      }

      if (crawler.platforms.length > 0) {
        md += `**Platforms:** ${crawler.platforms.join(', ')}\n`;
      }

      md += `**Results:** ${crawler.resultCount}\n\n---\n\n`;

      if (analysis) {
        md += `## Executive Summary\n\n${analysis.summary}\n\n`;

        md += `## Sentiment\n\n`;
        md += `**Overall:** ${analysis.overallSentiment}\n`;
        md += `- Positive: ${analysis.sentimentBreakdown.positive}%\n`;
        md += `- Neutral: ${analysis.sentimentBreakdown.neutral}%\n`;
        md += `- Negative: ${analysis.sentimentBreakdown.negative}%\n\n`;

        if (analysis.themes.length > 0) {
          md += `## Key Themes\n\n`;
          analysis.themes.forEach((theme, i) => {
            md += `### ${i + 1}. ${theme.name}\n`;
            md += `**Mentions:** ${theme.mentionCount} | **Sentiment:** ${theme.sentiment}\n`;
            if (theme.keyQuotes.length > 0) {
              md += `\n> "${theme.keyQuotes[0]}"\n`;
            }
            md += '\n';
          });
        }

        if (analysis.insights.length > 0) {
          md += `## Insights\n\n`;
          analysis.insights.forEach((insight) => {
            const icon =
              insight.type === 'opportunity'
                ? '🎯'
                : insight.type === 'threat'
                  ? '⚠️'
                  : insight.type === 'trend'
                    ? '📈'
                    : '✅';
            md += `${icon} **${insight.type.charAt(0).toUpperCase() + insight.type.slice(1).replace('_', ' ')}:** ${insight.title}\n`;
            md += `   *${insight.description}*\n`;
            if (insight.evidence.length > 0) {
              md += `   Evidence: ${insight.evidence.join(', ')}\n`;
            }
            md += '\n';
          });
        }

        if (analysis.recommendations.length > 0) {
          md += `## Recommendations\n\n`;
          analysis.recommendations.forEach((rec, i) => {
            md += `${i + 1}. ${rec}\n`;
          });
        }
      }

      return md;
    }
  };

  // Generate HTML content (for prototypes)
  const generateHTML = (): string => {
    if (isJob && isPrototype) {
      // For prototypes, return the raw HTML content
      return (content as ShareableJobResult).content;
    }

    // For other content, wrap markdown in a styled HTML document
    const markdown = generateMarkdown();
    const date = new Date().toISOString().split('T')[0];

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - ${date}</title>
  <style>
    :root {
      --primary: #4f46e5;
      --primary-light: #eef2ff;
      --text: #1f2937;
      --text-muted: #6b7280;
      --border: #e5e7eb;
      --bg: #ffffff;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: var(--text);
      background: var(--bg);
      padding: 2rem;
      max-width: 800px;
      margin: 0 auto;
    }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; color: var(--primary); }
    h2 { font-size: 1.5rem; margin: 2rem 0 1rem; border-bottom: 2px solid var(--primary-light); padding-bottom: 0.5rem; }
    h3 { font-size: 1.25rem; margin: 1.5rem 0 0.75rem; }
    p { margin-bottom: 1rem; }
    ul, ol { margin: 1rem 0; padding-left: 2rem; }
    li { margin-bottom: 0.5rem; }
    blockquote {
      border-left: 4px solid var(--primary);
      padding-left: 1rem;
      margin: 1rem 0;
      color: var(--text-muted);
      font-style: italic;
    }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { border: 1px solid var(--border); padding: 0.75rem; text-align: left; }
    th { background: var(--primary-light); font-weight: 600; }
    code { background: var(--primary-light); padding: 0.2rem 0.4rem; border-radius: 4px; font-size: 0.9em; }
    pre { background: #1f2937; color: #f9fafb; padding: 1rem; border-radius: 8px; overflow-x: auto; margin: 1rem 0; }
    pre code { background: none; padding: 0; color: inherit; }
    hr { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
    .meta { color: var(--text-muted); font-size: 0.875rem; margin-bottom: 1rem; }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      background: var(--primary-light);
      color: var(--primary);
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 500;
      text-transform: capitalize;
    }
    .footer {
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border);
      color: var(--text-muted);
      font-size: 0.75rem;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="content">
    ${markdownToHTML(markdown)}
  </div>
  <div class="footer">
    Generated by pmkit • ${date}
  </div>
</body>
</html>`;
  };

  // Simple markdown to HTML converter
  const markdownToHTML = (md: string): string => {
    return md
      // Headers
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      // Bold
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      // Italic
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      // Blockquotes
      .replace(/^> (.*$)/gim, '<blockquote>$1</blockquote>')
      // Code blocks
      .replace(/```(\w+)?\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
      // Inline code
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      // Horizontal rules
      .replace(/^---$/gim, '<hr>')
      // Tables (basic support)
      .replace(/\|(.+)\|/g, (match) => {
        const cells = match
          .split('|')
          .filter((c) => c.trim())
          .map((c) => c.trim());
        if (cells.every((c) => /^[-:]+$/.test(c))) {
          return ''; // Skip separator row
        }
        const isHeader = match.includes('---');
        const tag = isHeader ? 'th' : 'td';
        return `<tr>${cells.map((c) => `<${tag}>${c}</${tag}>`).join('')}</tr>`;
      })
      // Lists
      .replace(/^\d+\. (.*$)/gim, '<li>$1</li>')
      .replace(/^- (.*$)/gim, '<li>$1</li>')
      // Paragraphs
      .replace(/\n\n/g, '</p><p>')
      // Line breaks
      .replace(/\n/g, '<br>');
  };

  // Copy to clipboard
  const copyToClipboard = async (format: 'markdown' | 'html' | 'text') => {
    let text: string;

    switch (format) {
      case 'markdown':
        text = generateMarkdown();
        break;
      case 'html':
        text = generateHTML();
        break;
      case 'text':
        // Plain text - strip markdown formatting
        text = generateMarkdown()
          .replace(/^#+\s/gm, '')
          .replace(/\*\*(.*?)\*\*/g, '$1')
          .replace(/\*(.*?)\*/g, '$1')
          .replace(/`([^`]+)`/g, '$1')
          .replace(/^>\s/gm, '')
          .replace(/^[-*]\s/gm, '• ');
        break;
    }

    await navigator.clipboard.writeText(text);
    setCopiedFormat(format);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  // Download file
  const downloadFile = (format: 'markdown' | 'html') => {
    const date = new Date().toISOString().split('T')[0];
    const typeName = isJob
      ? content.jobType.replace(/_/g, '-')
      : content.crawlerType.replace(/_/g, '-');

    let filename: string;
    let mimeType: string;
    let fileContent: string;

    if (format === 'markdown') {
      filename = `${typeName}-${date}.md`;
      mimeType = 'text/markdown';
      fileContent = generateMarkdown();
    } else {
      filename = `${typeName}-${date}.html`;
      mimeType = 'text/html';
      fileContent = generateHTML();
    }

    const blob = new Blob([fileContent], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Share2 className="h-5 w-5 text-cobalt-600" />
            Share {title}
          </DialogTitle>
          <DialogDescription>
            Export or copy your results to share with your team.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Download Section */}
          <div className="space-y-2">
            <h4 className="text-sm font-medium">Download</h4>
            <div className="flex gap-2">
              <Button
                variant="outline"
                className="flex-1 gap-2"
                onClick={() => downloadFile('markdown')}
              >
                <FileText className="h-4 w-4" />
                Markdown (.md)
              </Button>
              <Button
                variant="outline"
                className="flex-1 gap-2"
                onClick={() => downloadFile('html')}
              >
                <Code className="h-4 w-4" />
                HTML
              </Button>
            </div>
            {isPrototype && (
              <p className="text-xs text-muted-foreground">
                💡 HTML export includes the full interactive prototype
              </p>
            )}
          </div>

          <Separator />

          {/* Copy Section */}
          <div className="space-y-2">
            <h4 className="text-sm font-medium">Copy to Clipboard</h4>
            <div className="flex flex-col gap-2">
              <Button
                variant="outline"
                className="justify-start gap-2"
                onClick={() => copyToClipboard('markdown')}
              >
                {copiedFormat === 'markdown' ? (
                  <Check className="h-4 w-4 text-green-600" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
                Copy as Markdown
                {copiedFormat === 'markdown' && (
                  <Badge variant="secondary" className="ml-auto">
                    Copied!
                  </Badge>
                )}
              </Button>
              <Button
                variant="outline"
                className="justify-start gap-2"
                onClick={() => copyToClipboard('text')}
              >
                {copiedFormat === 'text' ? (
                  <Check className="h-4 w-4 text-green-600" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
                Copy as Plain Text
                {copiedFormat === 'text' && (
                  <Badge variant="secondary" className="ml-auto">
                    Copied!
                  </Badge>
                )}
              </Button>
              {isPrototype && (
                <Button
                  variant="outline"
                  className="justify-start gap-2"
                  onClick={() => copyToClipboard('html')}
                >
                  {copiedFormat === 'html' ? (
                    <Check className="h-4 w-4 text-green-600" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                  Copy HTML Code
                  {copiedFormat === 'html' && (
                    <Badge variant="secondary" className="ml-auto">
                      Copied!
                    </Badge>
                  )}
                </Button>
              )}
            </div>
          </div>

          <Separator />

          {/* Coming Soon */}
          <div className="rounded-lg border border-dashed p-3 text-center">
            <p className="text-sm text-muted-foreground">
              🔗 Shareable links coming soon
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
